[package]
name = "backend-common"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]

[dependencies.backend-web]
path = "../backend-web"
optional = true
